# Pandas

## Introduction to Pandas

Pandas is a Python library used for working with structured data such as tables and Excel datasets. It provides useful tools for reading, inspecting, cleaning, selecting, and analyzing data.

- It handles dataframe or excel sheet.

- Row - records
- Columns - attributes, features or vsriables

- excel sheet is known as dataset in technical term.

      - In excel sheet the data types is used are -

          number - statistics

          text - categorical attributes

## Importing Pandas

The `pandas` library is commonly imported using the alias `pd`. This alias makes Pandas functions shorter and easier to use throughout the notebook.

- It handles dataframe or excel sheet.

- Row - records
- Columns - attributes, features or vsriables

- excel sheet is known as dataset in technical term.

      - In excel sheet the data types is used are -

          number - statistics

          text - categorical attributes

In [1]:
import pandas as pd

### Checking the Pandas Version

This checks the installed Pandas version. It is useful for confirming which version is being used in the current Python environment.

In [2]:
pd.__version__

'3.0.3'

## Loading the Dataset

The dataset is loaded from an Excel file using `read_excel()`. The resulting object is stored in `df`, which will be used for the Pandas operations below.

In [3]:
from pathlib import Path

candidates = [
    Path("data_used.xlsx"),
    Path("03_Data_Analysis/03_Pandas/data_used.xlsx"),
]
data_path = next((path for path in candidates if path.is_file()), None)
if data_path is None:
    raise FileNotFoundError(
        "data_used.xlsx was not found. Launch Jupyter from the repository root "
        "or from 03_Data_Analysis/03_Pandas."
    )
df = pd.read_excel(data_path)

### Viewing the Dataset

Displaying `df` shows the tabular data stored in the DataFrame. This gives an initial view of the rows and columns available in the dataset.

In [4]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

### Checking the DataFrame Type

This checks the Python type of `df`. It confirms that the loaded Excel data is represented as a Pandas DataFrame.

In [5]:
type(df)

pandas.DataFrame

### Checking the Number of Rows

The `len()` function returns the number of rows in the DataFrame. This helps understand the size of the dataset.

In [6]:
len(df)

195

### Checking Column Names

`df.columns` displays the names of all columns in the DataFrame. Column names identify the attributes or features represented in the dataset.

In [7]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='str')

### Counting Columns

The length of `df.columns` gives the total number of columns. This is another way to check the width of the dataset.

In [8]:
len(df.columns)

5

### Checking DataFrame Shape

The `shape` attribute gives the dimensions of the DataFrame as `(rows, columns)`. It provides a quick summary of the dataset size.

In [9]:
df.shape # it will give the dimention (rows, columns)

(195, 5)

## Raw Data and Clean Data

Raw data is data as collected, and it may be complete or contain quality issues. Cleaned data has been checked and transformed for a particular analysis; it can still contain missing values when those are intentionally preserved.

- **Raw data:** data in its original collected form.
- **Cleaned data:** data processed according to documented rules for a specific analysis; cleaning does not always mean removing every missing value.

### Checking for Missing Values

`isnull()` checks each cell for a missing value. It returns a Boolean result indicating whether each value is null.

In [10]:
df.isnull() # check for any null value

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

### Counting Missing Values

Adding `sum()` to the null check counts missing values for each column. This makes it easier to identify columns that contain incomplete data.

In [11]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

### Reviewing Column Names

The column names are displayed again before inspecting the contents of the DataFrame. This helps connect the available attributes with the following operations.

In [12]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='str')

### Viewing the First Rows

`head()` displays the first few rows of the DataFrame. It is commonly used to quickly inspect the beginning of a dataset.

In [13]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

### Viewing the Last Rows

`tail()` displays the last few rows of the DataFrame. It helps inspect the ending records of the dataset.

In [14]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

### DataFrame Information

`info()` provides a compact summary of the DataFrame, including columns, non-null values, and data types. It is useful for understanding the structure of the dataset.

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    str
 1   CountryCode    195 non-null    str
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    str
dtypes: float64(2), str(3)
memory usage: 12.9 KB

### Selecting the First 2 Rows

`head(2)` limits the output to the first two rows. The number inside `head()` controls how many rows are displayed.

In [16]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

### Selecting the First 3 Rows

`head(3)` displays the first three rows of the DataFrame. This is useful when a small preview of the data is needed.

In [17]:
df.head(3)

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income

## Pandas Slicing and Indexing

Slicing is used to select particular rows or columns from a DataFrame. The following operations demonstrate different ways of selecting rows and individual columns.

Special method in OOPS concept which is python constructor in it.

# Slicing in Pandas

### Selecting All Rows

`df[:]` uses slicing to select the DataFrame rows. With no start or stop value specified, the complete row range is selected.

In [18]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

### Selecting a Row Range

`df[10:21]` selects rows using a start and stop position. The stop position is not included in Python slicing.

In [19]:
df[10:21]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income
20,Belarus,BLR,12.500,54.17000,Upper middle income

### Selecting Rows with a Step

This slice uses start, stop, and step values to select rows at regular intervals. It demonstrates how the step value can skip rows.

In [20]:
df[10:150:20]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
130  Netherlands         NLD     10.200      93.956400          High income

### Selecting Every 10th Row

`df[::10]` selects rows from the beginning using a step of 10. This is useful for taking a regularly spaced sample of rows.

In [21]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

### Reversing the Rows

A step of `-1` reverses the row order. This demonstrates reverse slicing in a DataFrame.

In [22]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

### Reverse Slicing with a Step

A negative step can also skip rows while moving backward. Here, the DataFrame is traversed in reverse using a larger step.

In [23]:
df[::-50]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
144,French Polynesia,PYF,16.393,56.8000,High income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
44,Czech Republic,CZE,10.200,74.1104,High income

### Reviewing the First Rows Again

The first three rows are displayed again before moving from row slicing to column selection. This provides a quick reference to the dataset.

In [24]:
df.head(3)

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income

## Selecting Columns

A single column can be selected using its column name. The result represents the values stored in that particular attribute.

In [25]:
df['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: str

### Selecting Multiple Columns

Multiple columns can be selected by passing their names inside a list. This creates a smaller DataFrame containing the selected columns.

In [26]:
df[['CountryName', 'CountryName']]

              CountryName           CountryName
0                   Aruba                 Aruba
1             Afghanistan           Afghanistan
2                  Angola                Angola
3                 Albania               Albania
4    United Arab Emirates  United Arab Emirates
..                    ...                   ...
190           Yemen, Rep.           Yemen, Rep.
191          South Africa          South Africa
192      Congo, Dem. Rep.      Congo, Dem. Rep.
193                Zambia                Zambia
194              Zimbabwe              Zimbabwe

[195 rows x 2 columns]

### Creating a Categorical DataFrame

Here, selected categorical columns are stored in a new DataFrame named `df_cat`. Keeping selected columns separately can make later analysis easier.

In [27]:
df_cat = df[['CountryName', 'CountryName', 'IncomeGroup']]
df_cat

              CountryName           CountryName          IncomeGroup
0                   Aruba                 Aruba          High income
1             Afghanistan           Afghanistan           Low income
2                  Angola                Angola  Upper middle income
3                 Albania               Albania  Upper middle income
4    United Arab Emirates  United Arab Emirates          High income
..                    ...                   ...                  ...
190           Yemen, Rep.           Yemen, Rep.  Lower middle income
191          South Africa          South Africa  Upper middle income
192      Congo, Dem. Rep.      Congo, Dem. Rep.           Low income
193                Zambia                Zambia  Lower middle income
194              Zimbabwe              Zimbabwe           Low income

[195 rows x 3 columns]

### Creating a Numerical DataFrame

Selected numerical columns are stored in `df_num`. This separates numerical attributes for focused analysis.

In [28]:
df_num = df[['BirthRate', 'InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

### Comparing Column Names

The column names of the original and selected DataFrames are displayed. This helps verify which attributes are present in each DataFrame.

In [29]:
print(df.columns)
print(df_cat.columns)
print(df_num.columns)

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='str')
Index(['CountryName', 'CountryName', 'IncomeGroup'], dtype='str')
Index(['BirthRate', 'InternetUsers'], dtype='str')

### Comparing DataFrame Shapes

The shapes of the original, categorical, and numerical DataFrames are compared. This shows how column selection changes the dimensions.

In [30]:
print(df.shape)
print(df_cat.shape)
print(df_num.shape)

(195, 5)
(195, 3)
(195, 2)

## Decribe - Decriptive Stats

### Descriptive Statistics

Descriptive statistics summarize numerical data using measures such as count, mean, standard deviation, minimum, and maximum. They provide a quick overview of the distribution of numerical columns.

Always works for numerical value.

### Describing Numerical Data

`describe()` generates descriptive statistics for numerical columns. It is useful for getting a statistical summary without calculating each measure separately.

In [31]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

### Describing Categorical Data

`describe()` is also applied to the categorical DataFrame. For categorical columns, the summary focuses on information such as count, unique values, top value, and frequency.

In [32]:
df_cat.describe()

       CountryName CountryName  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba       Aruba  High income
freq             1           1           67

### Reviewing Available Columns

The column names are checked before performing a calculation between numerical columns. This helps confirm the attributes being used.

In [33]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='str')

### Performing a Column Calculation

Two numerical columns are multiplied element by element. The result is a Pandas Series containing the calculated value for each row.

In [34]:
df.BirthRate * df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

## Insertion

### Storing the Calculation

The multiplication result is assigned to the variable `result`. This keeps the calculated Series available for later viewing.

In [35]:
result = df.BirthRate * df.InternetUsers

### Viewing the Calculation Result

The stored result is displayed. Each value corresponds to the calculation performed for the matching row.

In [36]:
result

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

### Reviewing the Original DataFrame

The original DataFrame is displayed before adding a new column. This makes it possible to compare the DataFrame before and after insertion.

In [37]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

### Inserting a New Column

A new column named `Calculation` is created from the multiplication of two existing columns. This demonstrates how a derived column can be added to a DataFrame.

In [38]:
df['Calculation'] = df.BirthRate * df.InternetUsers
df['Calculation']

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Name: Calculation, Length: 195, dtype: float64

### Viewing the Updated DataFrame

The DataFrame is displayed after the new column has been added. The calculated values are now part of the table.

In [39]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,Calculation
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,658.9400
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

### Checking Columns After Insertion

The column names are displayed to verify that the new column was added. This confirms the updated DataFrame structure.

In [40]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'Calculation'],
      dtype='str')

### Counting Columns After Insertion

The number of columns is checked again after insertion. Comparing this with the earlier count shows the change in DataFrame width.

In [41]:
len(df.columns)

6

## Deletion

### Deleting a Column

The `drop()` method removes the `Calculation` column from the DataFrame. The `axis` argument specifies that a column is being removed.

In [42]:
df = df.drop('Calculation', axis = 1) # axis = 0 means rows, axis = 1 means columns

### Viewing the DataFrame After Deletion

The DataFrame is displayed after removing the calculated column. This confirms the change made by `drop()`.

In [43]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

### Checking Columns After Deletion

The column names are displayed again to verify that `Calculation` is no longer present.

In [44]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='str')

## Renaming Columns

Column names can be changed by assigning a new list of names to `df.columns`. The number of new names must match the number of columns.

In [45]:
df.columns = ['a', 'b', 'c', 'd', 'e']

### Viewing the Renamed Columns

The first row is displayed after changing the column names. This shows the temporary names assigned to the DataFrame.

In [46]:
df.head(1)

       a    b       c     d            e
0  Aruba  ABW  10.244  78.9  High income

### Restoring Descriptive Column Names

The original descriptive column names are assigned again. This keeps the DataFrame easy to understand for the remaining operations.

In [47]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers', 'IncomeGroup']

### Checking the Restored Names

The first row is displayed after restoring the column names. This confirms the DataFrame is ready for the filtering section.

In [48]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

## Filter in Pandas

### Reviewing the Data Before Filtering

The first few rows are displayed before applying conditions. Filtering will be used to select rows based on column values.

In [49]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

### Creating a Filter Condition

This condition checks which rows have an `InternetUsers` value below 3. The result is a Boolean Series that can be used to filter the DataFrame.

In [50]:
df['InternetUsers'] < 3

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192     True
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

### Filtering Rows by Internet Usage

The Boolean condition is applied to the DataFrame to return only rows where `InternetUsers` is below 3. This demonstrates conditional row selection.

In [51]:
df[df['InternetUsers'] < 3]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
11,Burundi,BDI,44.151,1.3,Low income
52,Eritrea,ERI,34.800,0.9,Low income
55,Ethiopia,ETH,32.925,1.9,Low income
64,Guinea,GIN,37.337,1.6,Low income
117,Myanmar,MMR,18.119,1.6,Lower middle income
127,Niger,NER,49.661,1.7,Low income
154,Sierra Leone,SLE,36.729,1.7,Low income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
172,Timor-Leste,TLS,35.755,1.1,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income

### Counting Filtered Rows

`len()` is used on the filtered DataFrame to count how many rows satisfy the condition. This gives the size of the selected subset.

In [52]:
len(df[df['InternetUsers'] < 3])

11

### Filtering by Birth Rate

This condition selects rows where `BirthRate` is greater than 40. It demonstrates filtering using a different numerical column.

In [53]:
df[df['BirthRate'] > 40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

### Counting Rows with High Birth Rate

The length of the filtered DataFrame gives the number of rows where `BirthRate` is greater than 40.

In [54]:
len(df[df['BirthRate'] > 40])

12

### Applying Multiple Conditions

Two conditions are combined using `&` so that both conditions must be true. This demonstrates filtering with multiple numerical criteria.

In [55]:
df[(df.BirthRate > 40) & (df.InternetUsers < 2)]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11      Burundi         BDI     44.151            1.3  Low income
127       Niger         NER     49.661            1.7  Low income
156     Somalia         SOM     43.891            1.5  Low income

## Unique Values in a Column

`unique()` returns the distinct values present in a column. It is useful for inspecting the different categories available in a dataset.

In [56]:
df.IncomeGroup.unique()

<ArrowStringArray>
['High income', 'Low income', 'Upper middle income', 'Lower middle income']
Length: 4, dtype: str

### Counting Unique Values

`nunique()` returns the number of distinct values in a column. This gives a compact count of the categories present.

In [57]:
df.IncomeGroup.nunique()

4